# Generated by Django 4.0.5 on 2022-06-08 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='tierradehoja',
            fields=[
                ('sku', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='SKU')),
                ('nombreProducto', models.CharField(max_length=20, verbose_name='Nombre del producto')),
                ('precio', models.CharField(max_length=20, verbose_name='Precio')),
                ('Stock', models.CharField(blank=True, max_length=20, null=True, verbose_name='Stock disponible')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='macetero',
            fields=[
                ('sku', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='SKU')),
                ('nombreProducto', models.CharField(max_length=20, verbose_name='Nombre del producto')),
                ('precio', models.CharField(max_length=20, verbose_name='Precio')),
                ('Stock', models.CharField(blank=True, max_length=20, null=True, verbose_name='Stock disponible')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='flores',
            fields=[
                ('sku', models.CharField(max_length=12, primary_key=True, serialize=False, verbose_name='SKU')),
                ('nombreProducto', models.CharField(max_length=20, verbose_name='Nombre del producto')),
                ('precio', models.CharField(max_length=20, verbose_name='Precio')),
                ('Stock', models.CharField(blank=True, max_length=20, null=True, verbose_name='Stock disponible')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
