# Generated by Django 4.0.1 on 2022-06-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_macetero_categoria_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='Categoria',
            new_name='CategoriaId',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombreProducto',
            new_name='Nombredelproducto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='precio',
            new_name='Precio',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='sku',
            new_name='SKU',
        ),
    ]
